### ISSUE TITLE
Multiple Strike Support for Bump and Dump

### ISSUE THREAD

**Issue by danharrin** [ryanpag3/discord-tally-bot#3]
For example...
 - `!tb bump [name] 5` would increase `[name]` by 5
 - `!tb dump [name] 2` would decrease `[name]` by 2

I am happy to submit a PR for this after your approval of this feature.

**Comment by ryanpag3** [comment]
Thanks for giving me some feedback on this project! I'll be deploying a new build tonight and new functionality will be enabled asap.

**Comment by danharrin** [comment]
Thanks!
