### ISSUE TITLE
Displaying tally group has no description

### ISSUE THREAD

**Issue by amarpersaud** [ryanpag3/discord-tally-bot#78]
Tally group has no description when using "!tb tg-get [name]", but the description is properly displayed in the message during the group's creation. Some information redacted.

![image](https://user-images.githubusercontent.com/9306252/84470928-574a3c00-ac52-11ea-8769-3f1b72a60a7d.png)

**Comment by ryanpag3** [comment]
I'll get this fixed. Thanks for reporting!
