### ISSUE TITLE
Deficiencia del bot

### ISSUE THREAD

**Issue by Roddyv** [ryanpag3/discord-tally-bot#86]
Hoy 20/09/2020 el bot no ha funcionado para nada en los canales de discord, si pudieran arreglar o notificarnos lo que sucede sería marvilloso, muchas gracias, otra cosa, si pueden permitir que el bot cuente mas de 24H, llegadas a las 24h el bot reinicia el tiempo.

**Comment by ryanpag3** [comment]
Thanks for submitting an issue for this. It was my fault, forgot to pay the server bill. Fixed now. Muchos gracias por tu ayuda!
